# Generated by Django 5.1.7 on 2025-04-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_DnDnDB_app', '0002_pagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedata',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
